const owners = [
  {
    _id: '45lZQXnOz38dJLp7',
    name: 'Dr. Wyman Runolfsson',
    address: '704 Hal Groves',
    phone: '1-886-203-7196 x1108',
    email: 'kristina48@hotmail.com',
  },
  {
    _id: 'Rmplca4avD8yurgP',
    name: 'Fleta Toy',
    address: '7534 Stehr Heights',
    phone: '027-842-0786',
    email: 'cesar_morar@gmail.com',
  },
  {
    _id: 'Vl71oE71brSPUCqc',
    name: 'Ms. Rhea Jones',
    address: '882 Al Way',
    phone: '(810) 118-0235 x022',
    email: 'johnnie.hessel6@gmail.com',
  },
  {
    _id: 'WIMMjV39Juwh4mjZ',
    name: 'Darrick Erdman',
    address: '0555 Laila Forge',
    phone: '666.461.1706',
    email: 'jefferey_christiansen@hotmail.com',
  },
  {
    _id: 'imT1p0oJ3gU0Bo3n',
    name: 'Jeremy King',
    address: '724 Smitham Extensions',
    phone: '(960) 868-2968',
    email: 'santiago68@hotmail.com',
  },
  {
    _id: 'lwdoL7fUYFvuwVHH',
    name: 'Wilhelmine Schroeder',
    address: '30917 Arvel Mills',
    phone: '(375) 183-1937 x65980',
    email: 'boyd_cremin@yahoo.com',
  },
  {
    _id: 'qyNmpv1APh0yWbhq',
    name: 'Earnestine Witting',
    address: '7231 Pfannerstill Loaf',
    phone: '(157) 283-7985 x55714',
    email: 'charley_shields@hotmail.com',
  },
  {
    _id: 'ucVWG6wTiYeb8fmB',
    name: 'Jeanette Turcotte MD',
    address: '229 Schroeder Cove',
    phone: '(627) 079-1265',
    email: 'erling.bayer@hotmail.com',
  },
  {
    _id: 'xL7WwOYbHrligynv',
    name: 'Tavares Lubowitz DVM',
    address: '05735 Zieme Field',
    phone: '079-750-1876',
    email: 'antwan_stehr28@yahoo.com',
  },
  {
    _id: 'z4CxyHolWfHmm1tq',
    name: 'Garrison Cremin MD',
    address: '61088 Lakin Place',
    phone: '(418) 322-1738 x735',
    email: 'bette73@gmail.com',
  },
];

const pets = [
  {
    _id: '28giQdcFlmx1yscH',
    name: 'Yundt',
    age: 8,
    color: 'maroon',
    breed: 'Rice',
    ownerId: '45lZQXnOz38dJLp7',
  },
  {
    _id: 'xCsoKQ9OcIqRqu6V',
    name: 'Feeney',
    age: 3,
    color: 'maroon',
    breed: 'Jacobi',
    ownerId: '45lZQXnOz38dJLp7',
  },
  {
    _id: '3AP71y6Xwyyr2q5a',
    name: 'Stiedemann',
    age: 9,
    color: 'azure',
    breed: 'Padberg',
    ownerId: '45lZQXnOz38dJLp7',
  },
  {
    _id: '4H69TSvKgF9SWgoa',
    name: 'Abbott',
    age: 2,
    color: 'turquoise',
    breed: 'Ankunding',
    ownerId: 'Rmplca4avD8yurgP',
  },
  {
    _id: '4S2AOCNKQ3NaubWb',
    name: 'Nicolas',
    age: 3,
    color: 'green',
    breed: 'Marquardt',
    ownerId: 'Rmplca4avD8yurgP',
  },
  {
    _id: '5wKOClAu4bE0lP6g',
    name: 'Oberbrunner',
    age: 5,
    color: 'purple',
    breed: 'Collins',
    ownerId: 'Rmplca4avD8yurgP',
  },
  {
    _id: '9aGhVoW156CnIBlD',
    name: 'Stokes',
    age: 4,
    color: 'black',
    breed: 'Kovacek',
    ownerId: 'Vl71oE71brSPUCqc',
  },
  {
    _id: 'AI0y5m5uR4uJ6LoO',
    name: 'Armstrong',
    age: 1,
    color: 'orange',
    breed: 'MacGyver',
    ownerId: 'Vl71oE71brSPUCqc',
  },
  {
    _id: 'D2Z87TSzUqYiYy9M',
    name: 'Terry',
    age: 7,
    color: 'gold',
    breed: 'Kshlerin',
    ownerId: 'Vl71oE71brSPUCqc',
  },
  {
    _id: 'Ehd8ry9SKghrYoss',
    name: 'Durgan',
    age: 4,
    color: 'white',
    breed: 'Ebert',
    ownerId: 'WIMMjV39Juwh4mjZ',
  },
  {
    _id: 'GXILkqFHhfIXhRlx',
    name: 'Carter',
    age: 8,
    color: 'ivory',
    breed: 'Kertzmann',
    ownerId: 'WIMMjV39Juwh4mjZ',
  },
  {
    _id: 'GyCZ6fZPp9ebRi4i',
    name: 'Rau',
    age: 8,
    color: 'black',
    breed: 'Fisher',
    ownerId: 'WIMMjV39Juwh4mjZ',
  },
  {
    _id: 'H8NdX4VVNuvAzXoa',
    name: 'Gottlieb',
    age: 5,
    color: 'mint green',
    breed: 'Kuhic',
    ownerId: 'imT1p0oJ3gU0Bo3n',
  },
  {
    _id: 'HoUQ7TJqJILvEdQr',
    name: 'Bergnaum',
    age: 1,
    color: 'orange',
    breed: 'Purdy',
    ownerId: 'imT1p0oJ3gU0Bo3n',
  },
  {
    _id: 'I06qEn1sGowoy7qR',
    name: 'Mraz',
    age: 6,
    color: 'violet',
    breed: 'Harber',
    ownerId: 'imT1p0oJ3gU0Bo3n',
  },
  {
    _id: '2eabYdJRPhMMNRUX',
    name: 'Ruecker',
    age: 7,
    color: 'orchid',
    breed: 'Fritsch',
    ownerId: 'lwdoL7fUYFvuwVHH',
  },
  {
    _id: 'KWuNelvtha153csA',
    name: 'White',
    age: 1,
    color: 'tan',
    breed: 'Williamson',
    ownerId: 'lwdoL7fUYFvuwVHH',
  },
  {
    _id: 'NiHroSWMyA1dmH8t',
    name: 'Tillman',
    age: 6,
    color: 'fuchsia',
    breed: 'Parisian',
    ownerId: 'lwdoL7fUYFvuwVHH',
  },
  {
    _id: 'OF9w4OadCOwTRvNF',
    name: 'Marquardt',
    age: 6,
    color: 'blue',
    breed: 'Weber',
    ownerId: 'qyNmpv1APh0yWbhq',
  },
  {
    _id: 'TKmAqJ64sRGlQm5w',
    name: 'Russel',
    age: 2,
    color: 'green',
    breed: 'Russel',
    ownerId: 'qyNmpv1APh0yWbhq',
  },
  {
    _id: 'TyRahyihzMPIIRnS',
    name: 'Legros',
    age: 6,
    color: 'plum',
    breed: 'Hills',
    ownerId: 'qyNmpv1APh0yWbhq',
  },
  {
    _id: 'WXhdphO4jAiAmiqG',
    name: 'Friesen',
    age: 3,
    color: 'orchid',
    breed: 'Nienow',
    ownerId: 'ucVWG6wTiYeb8fmB',
  },
  {
    _id: 'XxWOi3TyDojVzq4E',
    name: 'Koepp',
    age: 8,
    color: 'plum',
    breed: 'Stracke',
    ownerId: 'ucVWG6wTiYeb8fmB',
  },
  {
    _id: 'cLou6aFEPhP0nQTC',
    name: 'Anderson',
    age: 1,
    color: 'purple',
    breed: 'Kuhlman',
    ownerId: 'ucVWG6wTiYeb8fmB',
  },
  {
    _id: 'dmyHi7XtVmC7wcGc',
    name: 'Hessel',
    age: 7,
    color: 'cyan',
    breed: 'Quitzon',
    ownerId: 'xL7WwOYbHrligynv',
  },
  {
    _id: 'fNwMFEV0xXquFzzU',
    name: 'Kuvalis',
    age: 1,
    color: 'orchid',
    breed: 'Mertz',
    ownerId: 'xL7WwOYbHrligynv',
  },
  {
    _id: 'krUN6fbiv8vmZ8kQ',
    name: 'Gislason',
    age: 8,
    color: 'magenta',
    breed: 'Purdy',
    ownerId: 'xL7WwOYbHrligynv',
  },
  {
    _id: 'sTFEfSjqOeoCaQlV',
    name: 'Padberg',
    age: 9,
    color: 'sky blue',
    breed: 'Feil',
    ownerId: 'z4CxyHolWfHmm1tq',
  },
  {
    _id: 'tk4YFFCiK0weXYo4',
    name: 'Hyatt',
    age: 3,
    color: 'silver',
    breed: 'Effertz',
    ownerId: 'z4CxyHolWfHmm1tq',
  },
  {
    _id: 'JkVbIktQ0V1vxCKR',
    name: 'Bartoletti',
    age: 8,
    color: 'yellow',
    breed: 'Grady',
    ownerId: 'z4CxyHolWfHmm1tq',
  },
];

module.exports = { owners, pets };
